# Description: Docker compose file for development environment
# Usage: docker compose -f docker-compose.dev.yml up

services:
  s_snakes:
    image: s_snakes
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT:-42000}:42000"
