name: server tests

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test-server-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Build docker image
        run: timeout 5m docker build -t s_snakes .

