name: server tests

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test-server-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: docker build -t s_snakes .